# Generated by Django 3.2 on 2021-04-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0002_delete_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='college_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('course', models.CharField(choices=[('bca', 'BCA'), ('bba', 'BBA'), ('b.tech', 'B.Tech'), ('mca', 'MCA'), ('m.sc', 'M.Sc'), ('m.tech', 'M.Tech')], max_length=50)),
            ],
        ),
    ]
