# Generated by Django 3.2 on 2021-04-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_college_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('classes', models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV'), ('5', 'V'), ('6', 'VI'), ('7', 'VII'), ('8', 'VIII'), ('9', 'IX'), ('10', 'X'), ('11', 'XI'), ('12', 'XII')], max_length=50)),
            ],
        ),
    ]
